import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { IDBFactory, IDBObjectStore } from 'fake-indexeddb';
const ctx = vm.createContext({ console });
vm.runInContext(fs.readFileSync('src/storage.js', 'utf8'), ctx);
const create = ctx.StoreFlowStorage.create;
const state = JSON.stringify({ projects: [{ id: 'p', photo: 'data:image/jpeg;base64,' + 'a'.repeat(8 * 1024 * 1024) }], parts: [{ id: 'a', quantity: 17 }], orders: [], stockPallets: [], stocktakeResets: [{ id: 'reset', quantities: [{ partId: 'a', quantity: 10 }] }] });
const undo = JSON.stringify([{ id: 'u', changes: { collections: { parts: { records: [{ id: 'a', before: { id: 'a', quantity: 20 } }] } } } }]);
const legacy = new Map([['storeflow-state-v1', state], ['storeflow-undo-v1', undo]]);
const getLegacy = () => ({ getItem: key => legacy.get(key) ?? null });
const factory = new IDBFactory();
const db = create(factory, getLegacy);
const first = await db.init();
assert.equal(first.state, state); assert.equal(first.undo, undo);
assert.equal(legacy.get('storeflow-state-v1'), state);assert.equal(legacy.get('storeflow-undo-v1'), undo);
const second = create(factory, () => { throw new Error('Legacy access must not be needed again'); });
assert.equal((await second.init()).state, state);
await db.save(state.replace('17', '18'), undo);
await assert.rejects(second.save(state, undo), { name: 'ConflictError' });
const small = JSON.stringify({ projects: [], parts: [{ id: 'a', quantity: 19 }] });
await Promise.all([db.save(small, undo), db.save(small.replace('19', '20'), '[]')]);
const originalPut = IDBObjectStore.prototype.put;
IDBObjectStore.prototype.put = function (...args) { const request = originalPut.apply(this, args); this.transaction.abort(); return request; };
await assert.rejects(db.save(small, undo), { name: 'AbortError' });
IDBObjectStore.prototype.put = originalPut;
const reloaded = create(factory, getLegacy);
assert.equal((await reloaded.init()).state, small.replace('19', '20'));
assert.equal(legacy.get('storeflow-state-v1'), state);
const corruptFactory = new IDBFactory();let raw = '{broken';
const corrupt = create(corruptFactory, () => ({ getItem: key => key === 'storeflow-state-v1' ? raw : null }));
await assert.rejects(corrupt.init());raw = small;
const repaired = create(corruptFactory, () => ({ getItem: key => key === 'storeflow-state-v1' ? raw : null }));
assert.equal((await repaired.init()).state, small);
await assert.rejects(create(null, getLegacy).init(), { name: 'NotSupportedError' });
await assert.rejects(create(new IDBFactory(), () => { throw Object.assign(new Error('blocked'), { name: 'SecurityError' }); }).init(), { name: 'SecurityError' });
for (const connection of [db, second, reloaded, corrupt, repaired]) connection.close();
console.log('Database tests passed: >8 MB migration, exact photos/Undo/restore points, unchanged legacy data, restart, ordered saves, conflict protection, transaction abort rollback and fail-closed initialization.');
